"""Ask/tell lifecycle contracts shared by EvoCore optimizers."""

from evocore.lifecycle.archives import (
    ARCHIVE_SCHEMA_VERSION,
    ArchiveEntry,
    ArchiveExport,
    ArchivePolicy,
    CandidateArchive,
    DuplicatePolicy,
)
from evocore.lifecycle.batches import CandidateBatch, batch_id_from_seed
from evocore.lifecycle.checkpointing import (
    batch_from_checkpoint,
    batch_to_checkpoint,
    candidate_from_checkpoint,
    candidate_to_checkpoint,
    event_history_from_checkpoint,
    event_history_to_checkpoint,
    telemetry_from_checkpoint,
    telemetry_to_checkpoint,
)
from evocore.lifecycle.composition import derive_child_seed, inner_result_record, lineage_metadata
from evocore.lifecycle.conversion import candidate_to_solution, solution_to_candidate
from evocore.lifecycle.events import EventHistory, EventRecord, StopReason, append_run_stop_event
from evocore.lifecycle.external import (
    CandidateSnapshot,
    ExternalStateCapabilities,
    InjectionResult,
    PopulationSnapshot,
    WarmStartRecord,
    cached_records,
)
from evocore.lifecycle.policies import BudgetPolicy
from evocore.lifecycle.protocols import Evaluator, ExternalStateOptimizer, Optimizer
from evocore.lifecycle.records import (
    Candidate,
    CandidateOrigin,
    CandidateStatus,
    Direction,
    EvaluationConfidence,
    EvaluationContext,
    EvaluationRecord,
    EvaluationStage,
    ScoreObservation,
    is_state_update_confidence,
    score_for_direction,
)
from evocore.lifecycle.scheduler import BudgetScheduler
from evocore.lifecycle.selection import (
    DuplicateSelectionPolicy,
    FamilyQuota,
    MissingMetadataPolicy,
    SelectionDecision,
    SelectionResult,
    SpecialistCap,
    select_candidates,
)
from evocore.lifecycle.stopping import (
    CompositeStopPolicy,
    ConvergencePolicy,
    EvaluationLimitPolicy,
    NoImprovementPolicy,
    StopDecision,
    StopPolicy,
)
from evocore.lifecycle.telemetry import (
    AcceptanceDecision,
    OptimizationTelemetry,
    OptimizerStateSummary,
    UpdateResult,
)

__all__ = [
    "ARCHIVE_SCHEMA_VERSION",
    "AcceptanceDecision",
    "ArchiveEntry",
    "ArchiveExport",
    "ArchivePolicy",
    "BudgetPolicy",
    "BudgetScheduler",
    "Candidate",
    "CandidateArchive",
    "CandidateBatch",
    "CandidateOrigin",
    "CandidateSnapshot",
    "CandidateStatus",
    "CompositeStopPolicy",
    "ConvergencePolicy",
    "Direction",
    "DuplicatePolicy",
    "DuplicateSelectionPolicy",
    "EvaluationConfidence",
    "EvaluationContext",
    "EvaluationLimitPolicy",
    "EvaluationRecord",
    "EvaluationStage",
    "Evaluator",
    "EventHistory",
    "EventRecord",
    "ExternalStateCapabilities",
    "ExternalStateOptimizer",
    "FamilyQuota",
    "InjectionResult",
    "MissingMetadataPolicy",
    "NoImprovementPolicy",
    "OptimizationTelemetry",
    "Optimizer",
    "OptimizerStateSummary",
    "PopulationSnapshot",
    "ScoreObservation",
    "SelectionDecision",
    "SelectionResult",
    "SpecialistCap",
    "StopDecision",
    "StopPolicy",
    "StopReason",
    "UpdateResult",
    "WarmStartRecord",
    "append_run_stop_event",
    "batch_from_checkpoint",
    "batch_id_from_seed",
    "batch_to_checkpoint",
    "cached_records",
    "candidate_from_checkpoint",
    "candidate_to_checkpoint",
    "candidate_to_solution",
    "derive_child_seed",
    "event_history_from_checkpoint",
    "event_history_to_checkpoint",
    "inner_result_record",
    "is_state_update_confidence",
    "lineage_metadata",
    "score_for_direction",
    "select_candidates",
    "solution_to_candidate",
    "telemetry_from_checkpoint",
    "telemetry_to_checkpoint",
]
