"""Top-level evocore package exports."""

from importlib import metadata as _metadata

try:
    __version__ = _metadata.version("evocore")
except _metadata.PackageNotFoundError:
    __version__ = "0.7.0"

from evocore import _core
from evocore._core import (
    OP_CMAES_ASK,
    OP_CROSSOVER,
    OP_CROSSOVER_PROB,
    OP_INIT,
    OP_MULTI_RUN,
    OP_MUTATION,
    OP_SELECTION,
    BinaryIndividual,
    FloatIndividual,
    IntegerIndividual,
    py_derive_seed,
)
from evocore.callbacks import (
    Callback,
    CheckpointCallback,
    EarlyStopping,
    GenerationInfo,
    MetricsLogger,
    ProgressBar,
)
from evocore.core import (
    CheckpointError,
    ConfigurationError,
    ConfigurationWarning,
    ConvergenceError,
    EvocoreError,
    FitnessError,
    FitnessWarning,
    ParallelError,
    ProcessParallel,
    ThreadParallel,
)
from evocore.lifecycle import (
    BudgetPolicy,
    BudgetScheduler,
    Candidate,
    CandidateOrigin,
    CandidateStatus,
    Direction,
    EvaluationConfidence,
    EvaluationContext,
    EvaluationRecord,
    EvaluationStage,
    Evaluator,
    OptimizationTelemetry,
    Optimizer,
    OptimizerStateSummary,
    ScoreObservation,
    UpdateResult,
)
from evocore.optimizers.cmaes import (
    CategoricalDistributionState,
    CMAESOptimizer,
    IntegerMarginDistribution,
)
from evocore.optimizers.ga import GeneticAlgorithmOptimizer
from evocore.results import (
    EventHistory,
    EventRecord,
    GenerationHistory,
    GenerationRecord,
    OptimizationBatchResult,
    OptimizationResult,
    ReproducibilityMetadata,
)
from evocore.search_space import (
    Gene,
    GeneKind,
    GeneSpace,
    GeneValue,
    OperatorCodec,
    Solution,
    SolutionSet,
)
from evocore.surrogates import InverseDistanceAdvisor, SurrogateScore

__all__ = [
    "OP_CMAES_ASK",
    "OP_CROSSOVER",
    "OP_CROSSOVER_PROB",
    "OP_INIT",
    "OP_MULTI_RUN",
    "OP_MUTATION",
    "OP_SELECTION",
    "BinaryIndividual",
    "BudgetPolicy",
    "BudgetScheduler",
    "CMAESOptimizer",
    "Callback",
    "Candidate",
    "CandidateOrigin",
    "CandidateStatus",
    "CategoricalDistributionState",
    "CheckpointCallback",
    "CheckpointError",
    "ConfigurationError",
    "ConfigurationWarning",
    "ConvergenceError",
    "Direction",
    "EarlyStopping",
    "EvaluationConfidence",
    "EvaluationContext",
    "EvaluationRecord",
    "EvaluationStage",
    "Evaluator",
    "EventHistory",
    "EventRecord",
    "EvocoreError",
    "FitnessError",
    "FitnessWarning",
    "FloatIndividual",
    "Gene",
    "GeneKind",
    "GeneSpace",
    "GeneValue",
    "GenerationHistory",
    "GenerationInfo",
    "GenerationRecord",
    "GeneticAlgorithmOptimizer",
    "IntegerIndividual",
    "IntegerMarginDistribution",
    "InverseDistanceAdvisor",
    "MetricsLogger",
    "OperatorCodec",
    "OptimizationBatchResult",
    "OptimizationResult",
    "OptimizationTelemetry",
    "Optimizer",
    "OptimizerStateSummary",
    "ParallelError",
    "ProcessParallel",
    "ProgressBar",
    "ReproducibilityMetadata",
    "ScoreObservation",
    "Solution",
    "SolutionSet",
    "SurrogateScore",
    "ThreadParallel",
    "UpdateResult",
    "__version__",
    "_core",
    "py_derive_seed",
]
